---
title: "Countries of the World"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Countries of the world

In the world we live, despite of its big diversity, we can find a serie of common characteristics which allow us to get useful information about the situation of a country.

The goal of this App is trying to show an interactive perspective about these characteristics, such as demographics, geographics, politicals, economicals, culturals or others, respecting the different countries of the world

The app is composed by four main tabs:

* The **Overview of the data** tab contains two substabs:

    + *Summary* shows a global descriptive analysis comparison of the different variables presented in the dataset.
    + *Table* presents the data in which we can look for specific numeric information respect to the different variables. As well, we have the option to select number of entries we want to see. 

* The **Global Maps** tab allows to get information about the densities of the countries by variable.

* The **Region** panel exposes a comparison of the Agriculture, Service and Industrial sector  by regions. 

* The **Classification by countries** tab shows a comparison of four different countries taking into account the GDP, population, literacy and Netmigration. 

As a secondary tab, there is one for references.